[package]
name = "haproxy-api"
version = "0.9.1"
authors = ["Aleksandr Orlenko <zxteam@pm.me>"]
edition = "2021"
repository = "https://github.com/khvzak/haproxy-api-rs"
documentation = "https://docs.rs/haproxy-api"
readme = "README.md"
keywords = ["haproxy"]
license = "MIT"
description = """
HAProxy 2.8+ Lua API
"""

[package.metadata.docs.rs]
features = ["lua55"]

[workspace]
resolver = "2"
exclude = [
    "examples/async_serve_file",
    "examples/brotli",
    "examples/simple",
]

[features]
default = ["async", "lua55"]
lua = ["dep:mlua"]
native = []
runtime = ["dep:tokio"]
async = ["lua", "runtime", "mlua/async", "dep:pin-project-lite", "dep:futures-util", "dep:rustc-hash", "dep:dashmap"]
module = ["lua", "mlua/module"]
lua53 = ["lua", "mlua/lua53"]
lua54 = ["lua", "mlua/lua54"]
lua55 = ["lua", "mlua/lua55"]

[dependencies]
mlua = { version = "0.12", optional = true, features = ["serde", "error-send"] }
tokio = { version = "1.53", features = ["net", "io-util", "sync", "rt-multi-thread"], optional = true }
pin-project-lite = { version = "0.2", optional = true }
futures-util = { version = "0.3", optional = true }
rustc-hash = { version = "2.1", optional = true }
dashmap = { version = "6.2", optional = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[[test]]
name = "transaction_boundary"
path = "tests/transaction_boundary.rs"
required-features = ["lua"]
